# should the server owner want a lobby world to be the initial spawning world
lobby: true
end_portal_price: 100000
max_player_warps: 3
play_time_key_countdown: 14400 # this is in seconds
island:
  starting_border_radius: 60
  show_seed_price: 25000
  expand_price: 2000 # price per block - 10 blocks means 10 * price
warps:
  server:
    - name: "keys"
      world: "lobby"
      x: 0.5
      y: 44
      z: 0.5
  reserved_names:
    - "warp"
    - "spawn"
    - "shop"
    - "trade"
    - "trade_hall"
    - "pvp_arena"
    - "pvp"
    - "end"
    - "the_end"
    - "end_portal"
    - "nether"
    - "the_nether"
    - "create"
    - "list"
key_chests:
  - name: "PLAYTIME_KEY"
    display_name: "Playtime Key"
    world: "lobby"
    x: 0
    y: 44
    z: 6
