name: SimpleSkyblock
version: '0.0.6'
main: dev.ricr.skyblock.SimpleSkyblock
api-version: '1.21'
author: ricdotnet
description: A simple skyblock plugin that generates islands for new players

commands:
  balance:
    description: Get your economy balance
    usage: /balance
    permission: simpleskyblock.balance
    aliases: [ bal ]
  pay:
    description: Pay or give money to another player
    usage: /pay
    permission: simpleskyblock.pay
  shop:
    description: Open the shop GUI
    usage: /shop
    permission: simpleskyblock.shop
  reloadshop:
    description: Reload the shop config
    usage: /reloadshop
  leaderboard:
    description: View the leaderboard
    usage: /leaderboard
    aliases: [ baltop ]
  gamble:
    description: Gamble some money
    usage: /gamble
  auctionhouse:
    description: Open the auction house GUI
    usage: /auctionhouse
    aliases: [ ah ]
  island:
    description: Get player's island menu
    usage: /island
    aliases: [ is ]

permissions:
  simpleskyblock.balance:
    description: Allows players to check their economy balance
    default: true
  simpleskyblock.pay:
    description: Allows players to pay other players
    default: true
  simpleskyblock.shop:
    description: Allows players to open the shop GUI
    default: true
  reloadshop:
    description: Allows admins to reload the shop config
    default: op
  leaderboard:
    description: Allows players to view the balance leaderboard
    default: true
  gamble:
    description: Allows players to gamble money
    default: true
  auctionhouse:
    description: Allows players to open the auction house GUI
    default: true
  island:
    description: Allows players to open the island menu
    default: true