main: dev.ricr.skyblock.SimpleSkyblock
name: SimpleSkyblock
version: '0.1.0'
api-version: '1.21'
author: ricdotnet
load: STARTUP
description: A simple skyblock plugin that, all batteries included, includes island generator, world management, economy, shop, auction house and more.

commands:
  lobby:
    description: Go back to the lobby
    usage: /lobby
    aliases: [ spawn ]
  balance:
    description: Get your economy balance
    usage: /balance
    aliases: [ bal ]
  shop:
    description: Open the shop GUI
    usage: /shop
  leaderboard:
    description: View the leaderboard
    usage: /leaderboard
    aliases: [ baltop ]
  auctionhouse:
    description: Open the auction house GUI
    usage: /auctionhouse
    aliases: [ ah ]

permissions:
  lobby:
    description: Teleports players back to the lobby or server spawn
    default: true
  balance:
    description: Allows players to check their economy balance
    default: true
  shop:
    description: Allows players to open the shop GUI
    default: true
  leaderboard:
    description: Allows players to view the balance leaderboard
    default: true
  auctionhouse:
    description: Allows players to open the auction house GUI
    default: true
